name: Auto rollback traffic from green to blue.
on:
  workflow_dispatch:
permissions:
  id-token: write 
  contents: read
jobs:
  auto-rollback:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/aws-setup
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - name: Perform Auto Rollback
        run: bun run rollback