name: Auto schedules traffic shifting from blue to green every 10 mins
on:
  schedule:
    - cron: '30 2 * * *'    # 2:30 AM UTC = 10:30 PM EDT (Ottawa)
    - cron: '30 14 * * *'   # 2:30 PM UTC = 10:30 AM EDT (Ottawa)
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  auto-scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/aws-setup
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - name: Perform Auto Scheduling
        run: bun run reschedule