name: CI Tests
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  running-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/default-setup
      - name: Run unit and integration tests
        run: bun test --coverage