name: CI Tests
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
permissions:
  id-token: write   # Required for OIDC
  contents: read
jobs:
  running-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Default Setup
        uses: ./.github/actions/default-setup
      - name: Run tests
        run: bun test