name: CI Tests
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  running-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up default state
        uses: ./.github/actions/default-state.action.yaml
      - name: Run tests
        run: bun test